FROM cypress/base
RUN mkdir -p /opt/justto-web
WORKDIR /opt/justto-web
COPY package.json .
RUN npm install

# Install chrome
RUN apt-get update
RUN apt-get install -y libappindicator1 fonts-liberation
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome*.deb

# copy spec files and website files
COPY public public
COPY src src
COPY tests tests
COPY .env .env
COPY vue.config.js vue.config.js
COPY styleguide.config.js styleguide.config.js
COPY cypress.json cypress.json

# rerun E2E tests only if any of the previous files change
RUN $(npm bin)/cypress run -b chrome -e BASE_URL=https://homol.justto.com.br
