FROM cypress/browsers:chrome69
RUN mkdir -p /opt/justto-web
WORKDIR /opt/justto-web
COPY package.json .
RUN npm install

# copy spec files and website files
COPY public public
COPY src src
COPY tests tests
COPY .env .env
COPY vue.config.js vue.config.js
COPY styleguide.config.js styleguide.config.js
COPY cypress.json cypress.json
COPY babel.config.js babel.config.js
ENV VUE_APP_BASE_URL=https://justto.app

# rerun E2E tests only if any of the previous files change
#RUN npx vue-cli-service test:e2e --headless --browser chrome
