export const CALL_STATUS = Object.freeze({
  ENQUEUED: 'ENQUEUED',
  WAITING_DIALER: 'WAITING_DIALER',
  WAITING_DIALER_DETAIL: 'WAITING_DIALER_DETAIL',
  WAITING_NEW_CALL: 'WAITING_NEW_CALL',
  RECEIVING_CALL: 'RECEIVING_CALL',
  ACTIVE_CALL: 'ACTIVE_CALL',
  COMPLETED_CALL: 'COMPLETED_CALL'
})
